CREATE TABLE app_users (
 username VARCHAR(100) PRIMARY KEY,
 password_hash VARCHAR(100) NOT NULL,
 role VARCHAR(20) NOT NULL CHECK (role IN ('READER', 'EDITOR')),
 enabled BOOLEAN NOT NULL DEFAULT TRUE
);
