spring.application.name=uptimerobot-api-rest
logging.level.root=INFO
logging.level.edu.rutmiit=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n

spring.graphql.graphiql.enabled=true

# Путь к GraphQL-endpoint
spring.graphql.path=/graphql

# Расположение GraphQL-схемы для Spring for GraphQL.
spring.graphql.schema.locations=classpath*:graphql/

# Расположение GraphQL-схемы для DGS.
# DGS использует свой собственный механизм поиска схемы, отдельный от Spring for GraphQL.
# По умолчанию: classpath*:schema/**/*.graphql* — нужно переопределить.
dgs.graphql.schema-locations=classpath*:graphql/**/*.graphqls

# Включаем интроспекцию схемы (удобно при разработке, отключите в продакшене)
spring.graphql.schema.introspection.enabled=true

check.executor.logging-enabled=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
