spring:
  application:
    name: uptimerobot-notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
          multiplier: 2.0
server:
  port: 8084

logging:
  level:
    root: INFO
    edu.rutmiit: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
